version: '3.6'

services:
  llama-gpt-api-70b:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 3000:3000
    volumes:
      - './models:/models'
      - './run.sh:/app/run.sh'
    environment:
      MODEL: '/models/llama-2-70b-chat.bin'
      MODEL_DOWNLOAD_URL: 'https://huggingface.co/TheBloke/Llama-2-70B-Chat-GGML/resolve/main/llama-2-70b-chat.ggmlv3.q4_0.bin'
      N_GPU_LAYERS: 64
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
