version: '3.6'

services:
  llama-gpt-api-7b:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 3000:3000
    volumes:
      - './models:/models'
      - './run.sh:/app/run.sh'
    environment:
      N_GPU_LAYERS: 64
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
